### ISSUE TITLE
Burpsuite does not recognise serial number

### ISSUE THREAD

**Issue by whycanInotChoseUsername** [mounibkamhaz/Burp-Suite#1]
Running Windows, I followed instructions by firstly running:
  `java --illegal-access=permit -Dfile.encoding=utf-8 -javaagent:"loader.jar" -noverify -jar "burpsuite_pro_v2021.8.4.jar"`

and BurpSuite opened asking for the license key.  Terminal window returned:
  `Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option --illegal-access=permit; support was removed in 17.0 Java HotSpot(TM) 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.`

I then used:
  `java -jar keygen.jar`

and the keygen opened.  Terminal window returned:
`C:\Users\me\Desktop\classeditorC:\Users\me\Desktop\classeditor\burpsuite_pro_v2021.8.4.jarC:\Users\me\Desktop\classeditor\burpsuite_pro_v2021.8.4.jarC:\Users\me\Desktop\classeditorC:\Users\me\Desktop\classeditor\burpsuite_pro_v2021.8.4.jarC:\Users\me\Desktop\classeditor\burpsuite_pro_v2021.8.4.jar`

I copied the license key in to the BurpSuite dialog and then clicked 'Next' and I get error message:

> The supplied license key was not recognised.  Please try re-entering your license key

**Comment by mounibkamhaz** [comment]
# Java HotSpot(TM) 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.

* 1) Try reinstall jdk to version 11
* 2) First must be copy request from keygen.jar and paste in Burpsuite, then choose manuale activation and copy request from Burpsuite and paste in the keygen.jar, then the last step is copy response from keygen.jar and paste in Burpsuite ...

Happy Hacking!
